spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/invoice_db?autoReconnect=true&useSSL=false
    username: root
    password: mysqlpass
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    